### ISSUE TITLE
Basic Implementation - Device Agent

### ISSUE THREAD

**Issue by ryanpepe2000** [ryanpepe2000/mscs710-backend#16]
The goal of basic implementation is to create a device agent which can communicate with our backend server. This implementation will simply collect cpu/disk/memory usage and send a POST to our server.

The implementation will be in a file called 'agent.py' and this will be the convention for each agent utilized. If all of the agent implementation can be stored in one file, then that is the only file that will be in our project directory.

**Comment by casaltarelli** [comment]
Good work! Approved.
