### ISSUE TITLE
Database Population - Matrix Systems

### ISSUE THREAD

**Issue by casaltarelli** [ryanpepe2000/mscs710-backend#28]
**Purpose**
Currently we have been defining our schema within a respective database through the `/create-db` API. As we prepare to migrate our product into an AWS ECS container, we must ensure that this functionality is encompassed within the startup of Matrix Systems.

**Expected Behavior**
Locally upon starting Matrix Systems utilizing `docker-compose` or `run.py` Matrix Systems should be able to create all necessary tables within our remote database as well as populated any default data deemed necessary (Roles).

**Comment by ryanpepe2000** [comment]
The user agent is able to successfully post data to our route via the api
